- name: Set-Up Frontend Component
  hosts: FRONTEND
  become: yes
  roles:
    - frontend

- name: Set-Up Mongodb Component
  hosts: MONGODB
  become: yes
  roles:
    - mongodb

- name: Set-Up Catalogue Component
  hosts: CATALOGUE
  become: yes
  roles:
    - catalogue