-  name: Play level Variable
   hosts: all
   vars:
     URL: play.var.com
   tasks:
     - name: print URL
       ansible.builtin.debug:
         msg: URL is {{URL}}

- name: playlevel variable from a file
  hosts: all
  vars_files:
    - var-sample.yml
  tasks:
    - name: print the url
      ansible.builtin.debug:
        msg: URL is {{URL}}


- name: Register variable
  hosts: all
  tasks:
    - name: run a shell command
      ansible.builtin.shell: uptime
      register: OUT
    - name: print output of shell command
      ansible.builtin.debug:
        msg: "{{OUT.start}}"