

- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed


- name: Download and Extract content
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Cleaning Old HTML content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent


- name: Copying Frontend file in Nginx path
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Copyig Roboshop Configuration Files
  ansible.builtin.copy:
    src: localost.conf
    dest: /etc/nginx/default.d/localost.conf




- name: Starting Nginx Srvice
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enable: yes
