
#$ curl -s -L -o /tmp/catalogue.zip "https://github.com/roboshop-devops-project/catalogue/archive/main.zip"
#$ cd /home/roboshop
#$ unzip /tmp/catalogue.zip
#$ mv catalogue-main catalogue
#$ cd /home/roboshop/catalogue
#$ npm install
#
#```
#
#1. Update SystemD file with correct IP addresses
#
#Update `MONGO_DNSNAME` with MongoDB Server IP
#
#2. Now, lets set up the service with systemctl.
#
#```bash
#  # mv /home/roboshop/catalogue/systemd.service /etc/systemd/system/catalogue.service
#  # systemctl daemon-reload
#  # systemctl start catalogue
#  # systemctl enable catalogue
#
##```

- name: Creating Repo
  ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -

- name: Installing NodeJs
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Add application user
  ansible.builtin.user:
    name: roboshop
    comment: Roboshop Project Application user

- name: Download and Extract Catalogue content
  include_role:
    name: common
    tasks_from: download

- name: Cleaning Old Content
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: Copy app content
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
  become_user: roboshop   #roboshop becoming an user that has permissions only runs this task( for copy the content)

- name: Install NPM Dependencies
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop    # Here npm should run as normal user

- name: Copy systemd file
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service

- name: Start Catalogue service
  ansible.builtin.systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon_reload: yes
